export { createGradual, type Gradual, type GradualSync } from "./client";
export { evaluateFlag } from "./evaluator";
export type {
  EnvironmentSnapshot,
  EvalOutput,
  EvaluationBatchPayload,
  EvaluationContext,
  EvaluationEvent,
  EvaluationResult,
  EventsOptions,
  FlagOptions,
  GradualOptions,
  IsEnabledOptions,
  PollingOptions,
  RealtimeOptions,
  Reason,
  SnapshotFlag,
  SnapshotRollout,
  SnapshotRolloutVariation,
  SnapshotRuleCondition,
  SnapshotScheduleStep,
  SnapshotSegment,
  SnapshotTarget,
  SnapshotVariation,
  TargetingOperator,
} from "./types";
