export {
  createGradual,
  type EvalDetail,
  type Gradual,
  type GradualSync,
} from "./client";
export { evaluateFlag } from "./evaluator";
export type {
  EnvironmentSnapshot,
  EvalOutput,
  EvaluationBatchPayload,
  EvaluationContext,
  EvaluationEvent,
  EvaluationReason,
  EvaluationResult,
  EventsOptions,
  FlagOptions,
  GradualOptions,
  IsEnabledOptions,
  LegacyEvaluationReason,
  PollingOptions,
  Reason,
  SnapshotFlag,
  SnapshotRollout,
  SnapshotRolloutVariation,
  SnapshotRuleCondition,
  SnapshotSegment,
  SnapshotTarget,
  SnapshotVariation,
  TargetingOperator,
} from "./types";
