/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as OrganizationRouteImport } from './routes/_organization'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as AuthOnboardingRouteImport } from './routes/_auth/onboarding'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as OrganizationOrganizationSlugRouteRouteImport } from './routes/_organization/$organizationSlug/route'
import { Route as OrganizationOrganizationSlugIndexRouteImport } from './routes/_organization/$organizationSlug/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiFilesKeyRouteImport } from './routes/api/files/$key'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as OrganizationOrganizationSlugProjectRouteRouteImport } from './routes/_organization/$organizationSlug/_project/route'
import { Route as OrganizationOrganizationSlugProjectProjectSlugRouteRouteImport } from './routes/_organization/$organizationSlug/_project/$projectSlug/route'
import { Route as OrganizationOrganizationSlugProjectProjectSlugIndexRouteImport } from './routes/_organization/$organizationSlug/_project/$projectSlug/index'
import { Route as OrganizationOrganizationSlugProjectProjectSlugSettingsIndexRouteImport } from './routes/_organization/$organizationSlug/_project/$projectSlug/settings/index'
import { Route as OrganizationOrganizationSlugProjectProjectSlugFlagsIndexRouteImport } from './routes/_organization/$organizationSlug/_project/$projectSlug/flags/index'
import { Route as OrganizationOrganizationSlugProjectProjectSlugEnvironmentsIndexRouteImport } from './routes/_organization/$organizationSlug/_project/$projectSlug/environments/index'
import { Route as OrganizationOrganizationSlugProjectProjectSlugAudiencesIndexRouteImport } from './routes/_organization/$organizationSlug/_project/$projectSlug/audiences/index'
import { Route as OrganizationOrganizationSlugProjectProjectSlugApiIndexRouteImport } from './routes/_organization/$organizationSlug/_project/$projectSlug/api/index'
import { Route as OrganizationOrganizationSlugProjectProjectSlugAnalyticsIndexRouteImport } from './routes/_organization/$organizationSlug/_project/$projectSlug/analytics/index'
import { Route as OrganizationOrganizationSlugProjectProjectSlugFlagsFlagSlugIndexRouteImport } from './routes/_organization/$organizationSlug/_project/$projectSlug/flags/$flagSlug/index'
import { Route as OrganizationOrganizationSlugProjectProjectSlugEnvironmentsEnvironmentSlugIndexRouteImport } from './routes/_organization/$organizationSlug/_project/$projectSlug/environments/$environmentSlug/index'

const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/_organization',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const OrganizationOrganizationSlugRouteRoute =
  OrganizationOrganizationSlugRouteRouteImport.update({
    id: '/$organizationSlug',
    path: '/$organizationSlug',
    getParentRoute: () => OrganizationRoute,
  } as any)
const OrganizationOrganizationSlugIndexRoute =
  OrganizationOrganizationSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrganizationOrganizationSlugRouteRoute,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesKeyRoute = ApiFilesKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => ApiFilesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationOrganizationSlugProjectRouteRoute =
  OrganizationOrganizationSlugProjectRouteRouteImport.update({
    id: '/_project',
    getParentRoute: () => OrganizationOrganizationSlugRouteRoute,
  } as any)
const OrganizationOrganizationSlugProjectProjectSlugRouteRoute =
  OrganizationOrganizationSlugProjectProjectSlugRouteRouteImport.update({
    id: '/$projectSlug',
    path: '/$projectSlug',
    getParentRoute: () => OrganizationOrganizationSlugProjectRouteRoute,
  } as any)
const OrganizationOrganizationSlugProjectProjectSlugIndexRoute =
  OrganizationOrganizationSlugProjectProjectSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      OrganizationOrganizationSlugProjectProjectSlugRouteRoute,
  } as any)
const OrganizationOrganizationSlugProjectProjectSlugSettingsIndexRoute =
  OrganizationOrganizationSlugProjectProjectSlugSettingsIndexRouteImport.update(
    {
      id: '/settings/',
      path: '/settings/',
      getParentRoute: () =>
        OrganizationOrganizationSlugProjectProjectSlugRouteRoute,
    } as any,
  )
const OrganizationOrganizationSlugProjectProjectSlugFlagsIndexRoute =
  OrganizationOrganizationSlugProjectProjectSlugFlagsIndexRouteImport.update({
    id: '/flags/',
    path: '/flags/',
    getParentRoute: () =>
      OrganizationOrganizationSlugProjectProjectSlugRouteRoute,
  } as any)
const OrganizationOrganizationSlugProjectProjectSlugEnvironmentsIndexRoute =
  OrganizationOrganizationSlugProjectProjectSlugEnvironmentsIndexRouteImport.update(
    {
      id: '/environments/',
      path: '/environments/',
      getParentRoute: () =>
        OrganizationOrganizationSlugProjectProjectSlugRouteRoute,
    } as any,
  )
const OrganizationOrganizationSlugProjectProjectSlugAudiencesIndexRoute =
  OrganizationOrganizationSlugProjectProjectSlugAudiencesIndexRouteImport.update(
    {
      id: '/audiences/',
      path: '/audiences/',
      getParentRoute: () =>
        OrganizationOrganizationSlugProjectProjectSlugRouteRoute,
    } as any,
  )
const OrganizationOrganizationSlugProjectProjectSlugApiIndexRoute =
  OrganizationOrganizationSlugProjectProjectSlugApiIndexRouteImport.update({
    id: '/api/',
    path: '/api/',
    getParentRoute: () =>
      OrganizationOrganizationSlugProjectProjectSlugRouteRoute,
  } as any)
const OrganizationOrganizationSlugProjectProjectSlugAnalyticsIndexRoute =
  OrganizationOrganizationSlugProjectProjectSlugAnalyticsIndexRouteImport.update(
    {
      id: '/analytics/',
      path: '/analytics/',
      getParentRoute: () =>
        OrganizationOrganizationSlugProjectProjectSlugRouteRoute,
    } as any,
  )
const OrganizationOrganizationSlugProjectProjectSlugFlagsFlagSlugIndexRoute =
  OrganizationOrganizationSlugProjectProjectSlugFlagsFlagSlugIndexRouteImport.update(
    {
      id: '/flags/$flagSlug/',
      path: '/flags/$flagSlug/',
      getParentRoute: () =>
        OrganizationOrganizationSlugProjectProjectSlugRouteRoute,
    } as any,
  )
const OrganizationOrganizationSlugProjectProjectSlugEnvironmentsEnvironmentSlugIndexRoute =
  OrganizationOrganizationSlugProjectProjectSlugEnvironmentsEnvironmentSlugIndexRouteImport.update(
    {
      id: '/environments/$environmentSlug/',
      path: '/environments/$environmentSlug/',
      getParentRoute: () =>
        OrganizationOrganizationSlugProjectProjectSlugRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/device': typeof DeviceRoute
  '/$organizationSlug': typeof OrganizationOrganizationSlugProjectRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$key': typeof ApiFilesKeyRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/$organizationSlug/': typeof OrganizationOrganizationSlugIndexRoute
  '/$organizationSlug/$projectSlug': typeof OrganizationOrganizationSlugProjectProjectSlugRouteRouteWithChildren
  '/$organizationSlug/$projectSlug/': typeof OrganizationOrganizationSlugProjectProjectSlugIndexRoute
  '/$organizationSlug/$projectSlug/analytics/': typeof OrganizationOrganizationSlugProjectProjectSlugAnalyticsIndexRoute
  '/$organizationSlug/$projectSlug/api/': typeof OrganizationOrganizationSlugProjectProjectSlugApiIndexRoute
  '/$organizationSlug/$projectSlug/audiences/': typeof OrganizationOrganizationSlugProjectProjectSlugAudiencesIndexRoute
  '/$organizationSlug/$projectSlug/environments/': typeof OrganizationOrganizationSlugProjectProjectSlugEnvironmentsIndexRoute
  '/$organizationSlug/$projectSlug/flags/': typeof OrganizationOrganizationSlugProjectProjectSlugFlagsIndexRoute
  '/$organizationSlug/$projectSlug/settings/': typeof OrganizationOrganizationSlugProjectProjectSlugSettingsIndexRoute
  '/$organizationSlug/$projectSlug/environments/$environmentSlug/': typeof OrganizationOrganizationSlugProjectProjectSlugEnvironmentsEnvironmentSlugIndexRoute
  '/$organizationSlug/$projectSlug/flags/$flagSlug/': typeof OrganizationOrganizationSlugProjectProjectSlugFlagsFlagSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/device': typeof DeviceRoute
  '/login': typeof AuthLoginRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/$organizationSlug': typeof OrganizationOrganizationSlugIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$key': typeof ApiFilesKeyRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/$organizationSlug/$projectSlug': typeof OrganizationOrganizationSlugProjectProjectSlugIndexRoute
  '/$organizationSlug/$projectSlug/analytics': typeof OrganizationOrganizationSlugProjectProjectSlugAnalyticsIndexRoute
  '/$organizationSlug/$projectSlug/api': typeof OrganizationOrganizationSlugProjectProjectSlugApiIndexRoute
  '/$organizationSlug/$projectSlug/audiences': typeof OrganizationOrganizationSlugProjectProjectSlugAudiencesIndexRoute
  '/$organizationSlug/$projectSlug/environments': typeof OrganizationOrganizationSlugProjectProjectSlugEnvironmentsIndexRoute
  '/$organizationSlug/$projectSlug/flags': typeof OrganizationOrganizationSlugProjectProjectSlugFlagsIndexRoute
  '/$organizationSlug/$projectSlug/settings': typeof OrganizationOrganizationSlugProjectProjectSlugSettingsIndexRoute
  '/$organizationSlug/$projectSlug/environments/$environmentSlug': typeof OrganizationOrganizationSlugProjectProjectSlugEnvironmentsEnvironmentSlugIndexRoute
  '/$organizationSlug/$projectSlug/flags/$flagSlug': typeof OrganizationOrganizationSlugProjectProjectSlugFlagsFlagSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_organization': typeof OrganizationRouteWithChildren
  '/device': typeof DeviceRoute
  '/_organization/$organizationSlug': typeof OrganizationOrganizationSlugRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/_organization/$organizationSlug/_project': typeof OrganizationOrganizationSlugProjectRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$key': typeof ApiFilesKeyRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_organization/$organizationSlug/': typeof OrganizationOrganizationSlugIndexRoute
  '/_organization/$organizationSlug/_project/$projectSlug': typeof OrganizationOrganizationSlugProjectProjectSlugRouteRouteWithChildren
  '/_organization/$organizationSlug/_project/$projectSlug/': typeof OrganizationOrganizationSlugProjectProjectSlugIndexRoute
  '/_organization/$organizationSlug/_project/$projectSlug/analytics/': typeof OrganizationOrganizationSlugProjectProjectSlugAnalyticsIndexRoute
  '/_organization/$organizationSlug/_project/$projectSlug/api/': typeof OrganizationOrganizationSlugProjectProjectSlugApiIndexRoute
  '/_organization/$organizationSlug/_project/$projectSlug/audiences/': typeof OrganizationOrganizationSlugProjectProjectSlugAudiencesIndexRoute
  '/_organization/$organizationSlug/_project/$projectSlug/environments/': typeof OrganizationOrganizationSlugProjectProjectSlugEnvironmentsIndexRoute
  '/_organization/$organizationSlug/_project/$projectSlug/flags/': typeof OrganizationOrganizationSlugProjectProjectSlugFlagsIndexRoute
  '/_organization/$organizationSlug/_project/$projectSlug/settings/': typeof OrganizationOrganizationSlugProjectProjectSlugSettingsIndexRoute
  '/_organization/$organizationSlug/_project/$projectSlug/environments/$environmentSlug/': typeof OrganizationOrganizationSlugProjectProjectSlugEnvironmentsEnvironmentSlugIndexRoute
  '/_organization/$organizationSlug/_project/$projectSlug/flags/$flagSlug/': typeof OrganizationOrganizationSlugProjectProjectSlugFlagsFlagSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/device'
    | '/$organizationSlug'
    | '/login'
    | '/onboarding'
    | '/api/files'
    | '/api/upload'
    | '/api/auth/$'
    | '/api/files/$key'
    | '/api/trpc/$'
    | '/$organizationSlug/'
    | '/$organizationSlug/$projectSlug'
    | '/$organizationSlug/$projectSlug/'
    | '/$organizationSlug/$projectSlug/analytics/'
    | '/$organizationSlug/$projectSlug/api/'
    | '/$organizationSlug/$projectSlug/audiences/'
    | '/$organizationSlug/$projectSlug/environments/'
    | '/$organizationSlug/$projectSlug/flags/'
    | '/$organizationSlug/$projectSlug/settings/'
    | '/$organizationSlug/$projectSlug/environments/$environmentSlug/'
    | '/$organizationSlug/$projectSlug/flags/$flagSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/device'
    | '/login'
    | '/onboarding'
    | '/api/files'
    | '/api/upload'
    | '/$organizationSlug'
    | '/api/auth/$'
    | '/api/files/$key'
    | '/api/trpc/$'
    | '/$organizationSlug/$projectSlug'
    | '/$organizationSlug/$projectSlug/analytics'
    | '/$organizationSlug/$projectSlug/api'
    | '/$organizationSlug/$projectSlug/audiences'
    | '/$organizationSlug/$projectSlug/environments'
    | '/$organizationSlug/$projectSlug/flags'
    | '/$organizationSlug/$projectSlug/settings'
    | '/$organizationSlug/$projectSlug/environments/$environmentSlug'
    | '/$organizationSlug/$projectSlug/flags/$flagSlug'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_organization'
    | '/device'
    | '/_organization/$organizationSlug'
    | '/_auth/login'
    | '/_auth/onboarding'
    | '/api/files'
    | '/api/upload'
    | '/_organization/$organizationSlug/_project'
    | '/api/auth/$'
    | '/api/files/$key'
    | '/api/trpc/$'
    | '/_organization/$organizationSlug/'
    | '/_organization/$organizationSlug/_project/$projectSlug'
    | '/_organization/$organizationSlug/_project/$projectSlug/'
    | '/_organization/$organizationSlug/_project/$projectSlug/analytics/'
    | '/_organization/$organizationSlug/_project/$projectSlug/api/'
    | '/_organization/$organizationSlug/_project/$projectSlug/audiences/'
    | '/_organization/$organizationSlug/_project/$projectSlug/environments/'
    | '/_organization/$organizationSlug/_project/$projectSlug/flags/'
    | '/_organization/$organizationSlug/_project/$projectSlug/settings/'
    | '/_organization/$organizationSlug/_project/$projectSlug/environments/$environmentSlug/'
    | '/_organization/$organizationSlug/_project/$projectSlug/flags/$flagSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  OrganizationRoute: typeof OrganizationRouteWithChildren
  DeviceRoute: typeof DeviceRoute
  ApiFilesRoute: typeof ApiFilesRouteWithChildren
  ApiUploadRoute: typeof ApiUploadRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_organization': {
      id: '/_organization'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_organization/$organizationSlug': {
      id: '/_organization/$organizationSlug'
      path: '/$organizationSlug'
      fullPath: '/$organizationSlug'
      preLoaderRoute: typeof OrganizationOrganizationSlugRouteRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/_organization/$organizationSlug/': {
      id: '/_organization/$organizationSlug/'
      path: '/'
      fullPath: '/$organizationSlug/'
      preLoaderRoute: typeof OrganizationOrganizationSlugIndexRouteImport
      parentRoute: typeof OrganizationOrganizationSlugRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$key': {
      id: '/api/files/$key'
      path: '/$key'
      fullPath: '/api/files/$key'
      preLoaderRoute: typeof ApiFilesKeyRouteImport
      parentRoute: typeof ApiFilesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_organization/$organizationSlug/_project': {
      id: '/_organization/$organizationSlug/_project'
      path: ''
      fullPath: '/$organizationSlug'
      preLoaderRoute: typeof OrganizationOrganizationSlugProjectRouteRouteImport
      parentRoute: typeof OrganizationOrganizationSlugRouteRoute
    }
    '/_organization/$organizationSlug/_project/$projectSlug': {
      id: '/_organization/$organizationSlug/_project/$projectSlug'
      path: '/$projectSlug'
      fullPath: '/$organizationSlug/$projectSlug'
      preLoaderRoute: typeof OrganizationOrganizationSlugProjectProjectSlugRouteRouteImport
      parentRoute: typeof OrganizationOrganizationSlugProjectRouteRoute
    }
    '/_organization/$organizationSlug/_project/$projectSlug/': {
      id: '/_organization/$organizationSlug/_project/$projectSlug/'
      path: '/'
      fullPath: '/$organizationSlug/$projectSlug/'
      preLoaderRoute: typeof OrganizationOrganizationSlugProjectProjectSlugIndexRouteImport
      parentRoute: typeof OrganizationOrganizationSlugProjectProjectSlugRouteRoute
    }
    '/_organization/$organizationSlug/_project/$projectSlug/settings/': {
      id: '/_organization/$organizationSlug/_project/$projectSlug/settings/'
      path: '/settings'
      fullPath: '/$organizationSlug/$projectSlug/settings/'
      preLoaderRoute: typeof OrganizationOrganizationSlugProjectProjectSlugSettingsIndexRouteImport
      parentRoute: typeof OrganizationOrganizationSlugProjectProjectSlugRouteRoute
    }
    '/_organization/$organizationSlug/_project/$projectSlug/flags/': {
      id: '/_organization/$organizationSlug/_project/$projectSlug/flags/'
      path: '/flags'
      fullPath: '/$organizationSlug/$projectSlug/flags/'
      preLoaderRoute: typeof OrganizationOrganizationSlugProjectProjectSlugFlagsIndexRouteImport
      parentRoute: typeof OrganizationOrganizationSlugProjectProjectSlugRouteRoute
    }
    '/_organization/$organizationSlug/_project/$projectSlug/environments/': {
      id: '/_organization/$organizationSlug/_project/$projectSlug/environments/'
      path: '/environments'
      fullPath: '/$organizationSlug/$projectSlug/environments/'
      preLoaderRoute: typeof OrganizationOrganizationSlugProjectProjectSlugEnvironmentsIndexRouteImport
      parentRoute: typeof OrganizationOrganizationSlugProjectProjectSlugRouteRoute
    }
    '/_organization/$organizationSlug/_project/$projectSlug/audiences/': {
      id: '/_organization/$organizationSlug/_project/$projectSlug/audiences/'
      path: '/audiences'
      fullPath: '/$organizationSlug/$projectSlug/audiences/'
      preLoaderRoute: typeof OrganizationOrganizationSlugProjectProjectSlugAudiencesIndexRouteImport
      parentRoute: typeof OrganizationOrganizationSlugProjectProjectSlugRouteRoute
    }
    '/_organization/$organizationSlug/_project/$projectSlug/api/': {
      id: '/_organization/$organizationSlug/_project/$projectSlug/api/'
      path: '/api'
      fullPath: '/$organizationSlug/$projectSlug/api/'
      preLoaderRoute: typeof OrganizationOrganizationSlugProjectProjectSlugApiIndexRouteImport
      parentRoute: typeof OrganizationOrganizationSlugProjectProjectSlugRouteRoute
    }
    '/_organization/$organizationSlug/_project/$projectSlug/analytics/': {
      id: '/_organization/$organizationSlug/_project/$projectSlug/analytics/'
      path: '/analytics'
      fullPath: '/$organizationSlug/$projectSlug/analytics/'
      preLoaderRoute: typeof OrganizationOrganizationSlugProjectProjectSlugAnalyticsIndexRouteImport
      parentRoute: typeof OrganizationOrganizationSlugProjectProjectSlugRouteRoute
    }
    '/_organization/$organizationSlug/_project/$projectSlug/flags/$flagSlug/': {
      id: '/_organization/$organizationSlug/_project/$projectSlug/flags/$flagSlug/'
      path: '/flags/$flagSlug'
      fullPath: '/$organizationSlug/$projectSlug/flags/$flagSlug/'
      preLoaderRoute: typeof OrganizationOrganizationSlugProjectProjectSlugFlagsFlagSlugIndexRouteImport
      parentRoute: typeof OrganizationOrganizationSlugProjectProjectSlugRouteRoute
    }
    '/_organization/$organizationSlug/_project/$projectSlug/environments/$environmentSlug/': {
      id: '/_organization/$organizationSlug/_project/$projectSlug/environments/$environmentSlug/'
      path: '/environments/$environmentSlug'
      fullPath: '/$organizationSlug/$projectSlug/environments/$environmentSlug/'
      preLoaderRoute: typeof OrganizationOrganizationSlugProjectProjectSlugEnvironmentsEnvironmentSlugIndexRouteImport
      parentRoute: typeof OrganizationOrganizationSlugProjectProjectSlugRouteRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface OrganizationOrganizationSlugProjectProjectSlugRouteRouteChildren {
  OrganizationOrganizationSlugProjectProjectSlugIndexRoute: typeof OrganizationOrganizationSlugProjectProjectSlugIndexRoute
  OrganizationOrganizationSlugProjectProjectSlugAnalyticsIndexRoute: typeof OrganizationOrganizationSlugProjectProjectSlugAnalyticsIndexRoute
  OrganizationOrganizationSlugProjectProjectSlugApiIndexRoute: typeof OrganizationOrganizationSlugProjectProjectSlugApiIndexRoute
  OrganizationOrganizationSlugProjectProjectSlugAudiencesIndexRoute: typeof OrganizationOrganizationSlugProjectProjectSlugAudiencesIndexRoute
  OrganizationOrganizationSlugProjectProjectSlugEnvironmentsIndexRoute: typeof OrganizationOrganizationSlugProjectProjectSlugEnvironmentsIndexRoute
  OrganizationOrganizationSlugProjectProjectSlugFlagsIndexRoute: typeof OrganizationOrganizationSlugProjectProjectSlugFlagsIndexRoute
  OrganizationOrganizationSlugProjectProjectSlugSettingsIndexRoute: typeof OrganizationOrganizationSlugProjectProjectSlugSettingsIndexRoute
  OrganizationOrganizationSlugProjectProjectSlugEnvironmentsEnvironmentSlugIndexRoute: typeof OrganizationOrganizationSlugProjectProjectSlugEnvironmentsEnvironmentSlugIndexRoute
  OrganizationOrganizationSlugProjectProjectSlugFlagsFlagSlugIndexRoute: typeof OrganizationOrganizationSlugProjectProjectSlugFlagsFlagSlugIndexRoute
}

const OrganizationOrganizationSlugProjectProjectSlugRouteRouteChildren: OrganizationOrganizationSlugProjectProjectSlugRouteRouteChildren =
  {
    OrganizationOrganizationSlugProjectProjectSlugIndexRoute:
      OrganizationOrganizationSlugProjectProjectSlugIndexRoute,
    OrganizationOrganizationSlugProjectProjectSlugAnalyticsIndexRoute:
      OrganizationOrganizationSlugProjectProjectSlugAnalyticsIndexRoute,
    OrganizationOrganizationSlugProjectProjectSlugApiIndexRoute:
      OrganizationOrganizationSlugProjectProjectSlugApiIndexRoute,
    OrganizationOrganizationSlugProjectProjectSlugAudiencesIndexRoute:
      OrganizationOrganizationSlugProjectProjectSlugAudiencesIndexRoute,
    OrganizationOrganizationSlugProjectProjectSlugEnvironmentsIndexRoute:
      OrganizationOrganizationSlugProjectProjectSlugEnvironmentsIndexRoute,
    OrganizationOrganizationSlugProjectProjectSlugFlagsIndexRoute:
      OrganizationOrganizationSlugProjectProjectSlugFlagsIndexRoute,
    OrganizationOrganizationSlugProjectProjectSlugSettingsIndexRoute:
      OrganizationOrganizationSlugProjectProjectSlugSettingsIndexRoute,
    OrganizationOrganizationSlugProjectProjectSlugEnvironmentsEnvironmentSlugIndexRoute:
      OrganizationOrganizationSlugProjectProjectSlugEnvironmentsEnvironmentSlugIndexRoute,
    OrganizationOrganizationSlugProjectProjectSlugFlagsFlagSlugIndexRoute:
      OrganizationOrganizationSlugProjectProjectSlugFlagsFlagSlugIndexRoute,
  }

const OrganizationOrganizationSlugProjectProjectSlugRouteRouteWithChildren =
  OrganizationOrganizationSlugProjectProjectSlugRouteRoute._addFileChildren(
    OrganizationOrganizationSlugProjectProjectSlugRouteRouteChildren,
  )

interface OrganizationOrganizationSlugProjectRouteRouteChildren {
  OrganizationOrganizationSlugProjectProjectSlugRouteRoute: typeof OrganizationOrganizationSlugProjectProjectSlugRouteRouteWithChildren
}

const OrganizationOrganizationSlugProjectRouteRouteChildren: OrganizationOrganizationSlugProjectRouteRouteChildren =
  {
    OrganizationOrganizationSlugProjectProjectSlugRouteRoute:
      OrganizationOrganizationSlugProjectProjectSlugRouteRouteWithChildren,
  }

const OrganizationOrganizationSlugProjectRouteRouteWithChildren =
  OrganizationOrganizationSlugProjectRouteRoute._addFileChildren(
    OrganizationOrganizationSlugProjectRouteRouteChildren,
  )

interface OrganizationOrganizationSlugRouteRouteChildren {
  OrganizationOrganizationSlugProjectRouteRoute: typeof OrganizationOrganizationSlugProjectRouteRouteWithChildren
  OrganizationOrganizationSlugIndexRoute: typeof OrganizationOrganizationSlugIndexRoute
}

const OrganizationOrganizationSlugRouteRouteChildren: OrganizationOrganizationSlugRouteRouteChildren =
  {
    OrganizationOrganizationSlugProjectRouteRoute:
      OrganizationOrganizationSlugProjectRouteRouteWithChildren,
    OrganizationOrganizationSlugIndexRoute:
      OrganizationOrganizationSlugIndexRoute,
  }

const OrganizationOrganizationSlugRouteRouteWithChildren =
  OrganizationOrganizationSlugRouteRoute._addFileChildren(
    OrganizationOrganizationSlugRouteRouteChildren,
  )

interface OrganizationRouteChildren {
  OrganizationOrganizationSlugRouteRoute: typeof OrganizationOrganizationSlugRouteRouteWithChildren
}

const OrganizationRouteChildren: OrganizationRouteChildren = {
  OrganizationOrganizationSlugRouteRoute:
    OrganizationOrganizationSlugRouteRouteWithChildren,
}

const OrganizationRouteWithChildren = OrganizationRoute._addFileChildren(
  OrganizationRouteChildren,
)

interface ApiFilesRouteChildren {
  ApiFilesKeyRoute: typeof ApiFilesKeyRoute
}

const ApiFilesRouteChildren: ApiFilesRouteChildren = {
  ApiFilesKeyRoute: ApiFilesKeyRoute,
}

const ApiFilesRouteWithChildren = ApiFilesRoute._addFileChildren(
  ApiFilesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  OrganizationRoute: OrganizationRouteWithChildren,
  DeviceRoute: DeviceRoute,
  ApiFilesRoute: ApiFilesRouteWithChildren,
  ApiUploadRoute: ApiUploadRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
